### ISSUE TITLE
[feature request] - Enable scene export

### ISSUE THREAD

**Issue by mrrm92** [codetiger/Iyan3d#39]
Please, add an export feature for the animation, to export it as Collada or FBX (the best fit, with skeleton).

**Comment by mrrm92** [comment]
At least reply!

**Comment by mrrm92** [comment]
Bump?

**Comment by codetiger** [comment]
We are not continuing on this app at least for next 6 months. That's the reason why we open sourced it. If people are interested to contribute to this code, we will make the app free and continue working

**Comment by mrrm92** [comment]
But some versions ago, before the credits stuff, it was possible to export animated scenes. Why did you get it off?


Inviato dal mio dispositivo Samsung

-------- Messaggio originale --------
Da: Harishankar Narayanan <notifications@github.com> 
Data: 25/11/17  05:03  (GMT+01:00) 
A: codetiger/Iyan3d <Iyan3d@noreply.github.com> 
Cc: mrrm92 <chicochetal@gmail.com>, Author <author@noreply.github.com> 
Oggetto: Re: [codetiger/Iyan3d] [feature request] - Enable scene export (#39) 

We are not continuing on this app at least for next 6 months. That's the reason why we open sourced it. If people are interested to contribute to this code, we will make the app free and continue working

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/codetiger/Iyan3d","title":"codetiger/Iyan3d","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/codetiger/Iyan3d"}},"updates":{"snippets":[{"icon":"PERSON","message":"@codetiger in #39: We are not continuing on this app at least for next 6 months. That's the reason why we open sourced it. If people are interested to contribute to this code, we will make the app free and continue working"}],"action":{"name":"View Issue","url":"https://github.com/codetiger/Iyan3d/issues/39#issuecomment-346917171"}}}

**Comment by codetiger** [comment]
In Iyan 3d professional version, we never added export scene to other formats. You can only save and open it in the same app. If you are talking about free app, export scene only did video export

**Comment by mrrm92** [comment]
The previous version for Android, iirc, supported this


Inviato dal mio dispositivo Samsung

-------- Messaggio originale --------
Da: Harishankar Narayanan <notifications@github.com> 
Data: 25/11/17  12:41  (GMT+01:00) 
A: codetiger/Iyan3d <Iyan3d@noreply.github.com> 
Cc: mrrm92 <chicochetal@gmail.com>, Author <author@noreply.github.com> 
Oggetto: Re: [codetiger/Iyan3d] [feature request] - Enable scene export (#39) 

In Iyan 3d professional version, we never added export scene to other formats. You can only save and open it in the same app. If you are talking about free app, export scene only did video export

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/codetiger/Iyan3d","title":"codetiger/Iyan3d","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/codetiger/Iyan3d"}},"updates":{"snippets":[{"icon":"PERSON","message":"@codetiger in #39: In Iyan 3d professional version, we never added export scene to other formats. You can only save and open it in the same app. If you are talking about free app, export scene only did video export"}],"action":{"name":"View Issue","url":"https://github.com/codetiger/Iyan3d/issues/39#issuecomment-346935480"}}}

**Comment by codetiger** [comment]
No
