### ISSUE TITLE
[feature request] - Animation curves

### ISSUE THREAD

**Issue by ghost** [codetiger/Iyan3d#40]
Please, enable modification to the animation as curves and enable editing them (please see https://docs.blender.org/manual/en/dev/editors/graph_editor/introduction.html to fully understand what I mean).

**Comment by codetiger** [comment]
We would love to make Iyan 3D more professional but unfortunately with the bandwidth we have, animation curves are not in our roadmap at least for a year. I am taking this feature for our upcoming roadmap. Thanks for sharing.
