### ISSUE TITLE
jni code compilation error

### ISSUE THREAD

**Issue by KnIfER** [codetiger/Iyan3d#42]
[armeabi-v7a] Compile++ thumb: iyan3d <= iyan3d.cpp
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp: In function 'voi
d createDuplicateAssets(JNIEnv*, jclass, jobject)':
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:466:65: error: 'A
CTION_MULTI_NODE_ADDED' was not declared in this scope
             editorScene->actionMan->storeAddOrRemoveAssetAction(ACTION_MULTI_NO
DE_ADDED, 0);
                                                                 ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp: In function 'voi
d changedPropertyAtIndex(JNIEnv*, jclass, jobject, PROP_INDEX, Vector4, bool)':
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:577:66: error: 'c
lass SGNode' has no member named 'smoothTexture'
                 editorScene->nodes[editorScene->selectedNodeId]->smoothTexture
= status;
                                                                  ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp: In function 'voi
d Java_com_smackall_iyan3dPro_opengl_GL2JNILib_removeNode(JNIEnv*, jclass, jint,
 jboolean)':
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:1290:73: error: '
ACTION_TEXT_IMAGE_DELETE' was not declared in this scope
                     editorScene->actionMan->storeAddOrRemoveAssetAction(ACTION_
TEXT_IMAGE_DELETE, 0);
                                                                         ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:1292:73: error: '
ACTION_NODE_DELETED' was not declared in this scope
                     editorScene->actionMan->storeAddOrRemoveAssetAction(ACTION_
NODE_DELETED, 0);
                                                                         ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp: In function 'jbo
olean Java_com_smackall_iyan3dPro_opengl_GL2JNILib_importImageOrVideo(JNIEnv*, j
class, jint, jstring, jint, jint, jint, jboolean)':
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:1654:168: warning
: invalid conversion from 'jint {aka int}' to 'NODE_TYPE' [-fpermissive]
        SGNode* sgNode = editorScene->loader->loadNode(nodeType, 0,"","-1",asset
NameW,imgWidth, imgHeight,(int)actionType ,Vector4(imgWidth,imgHeight,0,0),"",is
TempNode);

        ^
In file included from F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/Iyan3d
EngineFiles/HeaderFiles/SGEditorScene.h:48:0,
                 from F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d
.cpp:2:
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/Iyan3dEngineFiles/HeaderFile
s/SGSceneLoader.h:37:13: note: initializing argument 1 of 'SGNode* SGSceneLoader
::loadNode(NODE_TYPE, int, std::__ndk1::string, std::__ndk1::string, std::__ndk1
::wstring, int, int, int, Vector4, std::__ndk1::string, bool)'
     SGNode* loadNode(NODE_TYPE type,int assetId, string meshPath, string textur
eName, std::wstring imagePath = L" ", int imgWidth = 0, int imgHeight = 0, int a
ctionType = OPEN_SAVED_FILE, Vector4 textColor = Vector4(0), string fontFilePath
 = "", bool isTempNode = false);
             ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:1663:69: error: '
ACTION_TEXT_IMAGE_ADD' was not declared in this scope
                 editorScene->actionMan->storeAddOrRemoveAssetAction(ACTION_TEXT
_IMAGE_ADD, 0);
                                                                     ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp: In function 'voi
d Java_com_smackall_iyan3dPro_opengl_GL2JNILib_importAdditionalLight(JNIEnv*, jc
lass, jint, jint)':
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:1687:69: error: '
ACTION_NODE_ADDED' was not declared in this scope
                 editorScene->actionMan->storeAddOrRemoveAssetAction(ACTION_NODE
_ADDED, assetId , "Light"+ to_string(lightCount));
                                                                     ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp: In function 'voi
d Java_com_smackall_iyan3dPro_opengl_GL2JNILib_undo(JNIEnv*, jclass, jobject)':
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:2037:14: error: '
ADD_INSTANCE_BACK' was not declared in this scope
         case ADD_INSTANCE_BACK:
              ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp: In function 'voi
d Java_com_smackall_iyan3dPro_opengl_GL2JNILib_redo(JNIEnv*, jclass, jobject)':
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:2068:28: error: '
ADD_INSTANCE_BACK' was not declared in this scope
         if (returnValue == ADD_INSTANCE_BACK)
                            ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp: In function 'voi
d Java_com_smackall_iyan3dPro_opengl_GL2JNILib_renderFrame(JNIEnv*, jclass, jobj
ect, jint, jint, jboolean, jboolean, jfloat, jfloat, jfloat)':
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:2116:63: warning:
 invalid conversion from 'const value_type* {aka const char*}' to 'char*' [-fper
missive]
         editorScene->renHelper->renderAndSaveImage(path.c_str(), false, (isImag
e) ? -1 : frame-1, Vector4(x,y,z,1.0));
                                                               ^
In file included from F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/Iyan3d
EngineFiles/HeaderFiles/SGEditorScene.h:43:0,
                 from F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d
.cpp:2:
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/Iyan3dEngineFiles/HeaderFile
s/RenderHelper.h:42:10: note: initializing argument 1 of 'void RenderHelper::ren
derAndSaveImage(char*, bool, int, Vector4)'
     void renderAndSaveImage(char *imagePath, bool isDisplayPrepared, int frame,
 Vector4 bgColor = Vector4(0.1, 0.1, 0.1, 1.0));
          ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp: In function 'jbo
olean Java_com_smackall_iyan3dPro_opengl_GL2JNILib_cloneSelectedAsset(JNIEnv*, j
class, jint, jint, jint, jint)':
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:2178:88: warning:
 invalid conversion from 'jint {aka int}' to 'ActionType' [-fpermissive]
             editorScene->loader->createInstance(sgNode, sgNode->getType(), asse
tAddType);

        ^
In file included from F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/Iyan3d
EngineFiles/HeaderFiles/SGEditorScene.h:48:0,
                 from F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d
.cpp:2:
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/Iyan3dEngineFiles/HeaderFile
s/SGSceneLoader.h:48:10: note: initializing argument 3 of 'void SGSceneLoader::c
reateInstance(SGNode*, NODE_TYPE, ActionType)'
     void createInstance(SGNode* sgNode, NODE_TYPE nType, ActionType actionType)
;
          ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:2181:69: error: '
ACTION_NODE_ADDED' was not declared in this scope
                 editorScene->actionMan->storeAddOrRemoveAssetAction(ACTION_NODE
_ADDED, sgNode->assetId);
                                                                     ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp: In function 'jin
t Java_com_smackall_iyan3dPro_opengl_GL2JNILib_smoothTexState(JNIEnv*, jclass)':

F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:2313:174: error:
'class SGNode' has no member named 'smoothTexture'
         int smoothTex = (editorScene->nodes[editorScene->selectedNodeId]->getPr
operty(IS_VERTEX_COLOR).value.x) ? -1 : (int)editorScene->nodes[editorScene->sel
ectedNodeId]->smoothTexture;

              ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp: In function 'jin
t Java_com_smackall_iyan3dPro_opengl_GL2JNILib_smoothTexStateWithId(JNIEnv*, jcl
ass, jint)':
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:2319:132: error:
'class SGNode' has no member named 'smoothTexture'
         int smoothTex = (editorScene->nodes[nodeId]->getProperty(IS_VERTEX_COLO
R).value.x) ? -1 : (int)editorScene->nodes[nodeId]->smoothTexture;

                                                    ^
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp: In function 'voi
d Java_com_smackall_iyan3dPro_opengl_GL2JNILib_setTextureSmoothStatus(JNIEnv*, j
class, jboolean)':
F:/scrhashing_music/Iyan3D-Android/app/src/main/jni/iyan3d.cpp:2327:62: error: '
class SGNode' has no member named 'smoothTexture'
             editorScene->nodes[editorScene->selectedNodeId]->smoothTexture = st
atus;
                                                              ^
make: *** [F:/scrhashing_music/Iyan3D-Android/app/src/main/obj/local/armeabi-v7a
/objs/iyan3d/iyan3d.o] Error 1

**Comment by codetiger** [comment]
Shall check and update the repo

**Comment by codetiger** [comment]
Plan for making professional version available for Android is not in the plan for near future.
