### ISSUE TITLE
Offline and apk

### ISSUE THREAD

**Issue by anonimo82** [codetiger/Iyan3d#43]
Please, will anyone make this app working without connection? 
And please, will anyone add animation export? (I don't mean rendering, but indeed save animated scene/mesh)

Finally, is it there any APK to download?

**Comment by anonimo82** [comment]
Sorry, I'll explain:
1) Add a button for getting as much credits as you want without paying (because completely removing the credits stuff, I guess it's much more work)
2) Enable rendering in HQ locally (on the device) by porting the backend
3) Add collada (.dae) scene export

Many thanks if you help.

**Comment by anonimo82** [comment]
I'm also offering paid work for this, see https://sites.google.com/view/iyan3d
Basically, I can pay up to 40 $ per week, so, in example, if you want 10 $ per hour, just work on this 4 hours per week.

**Comment by codetiger** [comment]
All these are done in the latest professional version app release
