### ISSUE TITLE
Android port 

### ISSUE THREAD

**Issue by imakegoodsuf2** [codetiger/Iyan3d#56]
Hi i seen what this app can do i would love a android port of this app

I think it deserves to be on android

**Comment by codetiger** [comment]
Thanks for your feedback @imakegoodsuf2 

I am struggling at planning for the future of this app. I've some interest in rewriting this app from ground up, however supporting Android is going to be big pain considering only me who is going to code everything. Let me consider Android during the planning and update you.

**Comment by nickmux** [comment]
> Thanks for your feedback @imakegoodsuf2
> 
> I am struggling at planning for the future of this app. I've some interest in rewriting this app from ground up, however supporting Android is going to be big pain considering only me who is going to code everything. Let me consider Android during the planning and update you.

hey uh its the person who made the android port request but is there any news on iyan 3d pro as a whole
